/*

    References

*/

const AMINOL_NODE_SIZE = 7.5
const AMINOL_NODE_WIDTH = AMINOL_NODE_SIZE * 1.25

const CHILD_NODE_X_OFFSET = (AMINOL_NODE_WIDTH * 1.5)
const CHILD_NODE_Y_OFFSET = (AMINOL_NODE_SIZE * 1.5)

const UPDATE_FPS = 12

const ENERGY_NATURAL_DECREASE = 0.01 / 1000

module.exports = {
    AMINOL_NODE_SIZE,
    AMINOL_NODE_WIDTH,
    CHILD_NODE_X_OFFSET,
    CHILD_NODE_Y_OFFSET,
    UPDATE_FPS,
    ENERGY_NATURAL_DECREASE
}